#!/bin/bash

X=`pwd`/$1 # caminho do arquivo contendo a query
F=`pwd`/Corpus/dofast4

: '
    $$ armazena o pid da shell atual, assim xxx$$
    cria um diretório com "nome único".
'
mkdir /tmp/xxx$$
rm -rf /tmp/dotf*line

: '
    ln -s <src> <dest> cria um link de <src> em <dest>.
'

ln -s `pwd`/Corpus/tar4 /tmp/xxx$$
ln -s `pwd`/dotf*line /tmp

cd /tmp/xxx$$

mkdir thing
cp $X thing/doc
: '
    cria o arquivo thing.tgz utilizando o conteúdo de thing
'
tar zcf thing.tgz thing

$F thing

cat thing.concordance
